name: Bug Report
description: Found a Bug that needs to be fixed?
labels: ["type: Bug Report"]
body:
  - type: markdown
    attributes:
      value: |-
        Please join the [Discord Server](https://discord.gg/ZptCBHeHyg) for questions.
        
        _Keep in mind that this isn't the place to learn Java._  
        _Please head over to [Stack Overflow](https://stackoverflow.com/questions/tagged/java) for your general programming questions._
  - type: checkboxes
    attributes:
      label: General
      description: You confirm to have made the following checks first.
      options:
        - label: I have checked for similar issues on the Issue-tracker.
          required: true
        - label: I have checked for PRs that might already address this issue.
          required: true
  - type: textarea
    attributes:
      label: "Expected Behaviour"
      description: "What did you expect InOsso to do?"
      placeholder: "InOsso should do ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reproduction Steps"
      description: |-
        Please add the steps you took to reproduce this problem.  
        Put "N/A" if you don't have a reproducible setup.
      placeholder: |-
        1. Do this.
        2. Do that.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Exception or Error"
      description: |-
        Share any Exception or Error you encountered.  
        Leave this blank or put "N/A" if you don't have an Exception or Error.
        
        The provided text will be rendered as code, so you don't have to provide a Code block for it.
      render: yesyes # Unknown code-names = no highlighting.
      placeholder: "java.lang.NullPointerException: null"
