blank_issues_enabled: false
contact_links:
  - name: Ask on Discord
    url: https://discord.gg/ZptCBHeHyg
    about: Get fast support for your questions in the Discord server.
  - name: InOsso Webpage
    url: https://www.casiebarie.dev/discord/inosso/
    about: Find more info about this bot on my website.