name: Deploy Bot

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      deploy: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH and Deploy Bot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" > /home/ubuntu/ghcr_token.txt
            chmod 600 /home/ubuntu/ghcr_token.txt
            cd /home/ubuntu
            ./update-bot.sh