name: Build, Push, and Deploy Bot

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/casiebarie/inosso-bot:latest .
          docker push ghcr.io/casiebarie/inosso-bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up ssh-agent
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

      - name: Set up GitHub Container Registry Authentication
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" > ghcr_token.txt
          scp ghcr_token.txt ubuntu@${{ secrets.ORACLE_HOST }}:/home/ubuntu/ghcr_token.txt

      - name: SSH into Oracle VM and update bot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Move the token file to the correct place
            mv /home/ubuntu/ghcr_token.txt /home/ubuntu/.ghcr_token

            # Run the update-bot.sh script which will use the token for Docker login
            chmod +x /home/ubuntu/update-bot.sh
            /home/ubuntu/update-bot.sh
