name: Validation
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      deploy: false
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}